### PR TITLE
[addpkg] dbeaver-ce

### PR DESCRIPTION
**Pull request by CurtisBelt**
## Feedback Needed
- DBeaver requires Java 1.8 or higher, but I went ahead and set the latest "jre9-openjdk" as the dependency to avoid having to select between versions during install. If it's frowned upon to not put the exact dependency, let me know.
- This is my first time creating a package, so any other review or feedback appreciated!

## Notes
- Used it myself successfully on two machines (x86_64)
- Adapted from https://aur.archlinux.org/cgit/aur.git/tree/?h=dbeaver-ce, retaining the previous maintainer credits.

### CODE REVIEW

**Comment by CurtisBelt** [comment]
Note that `pacman -Ss dbeaver` does contain

> community/dbeaver 4.2.5-1 [installed]
>     Free universal SQL Client for developers and database administrators
>     (community edition)

However this package has been [flagged as out-of-date](https://www.archlinux.org/packages/community/x86_64/dbeaver/) since 2017-11-27.

**Comment by CurtisBelt** [comment]
@lots0logs Anything else needed for this PR? Thanks!

**Comment by sum01** [comment]
The new version https://www.archlinux.org/packages/community-testing/x86_64/dbeaver/ is in testing.

**Comment by CurtisBelt** [comment]
@sum01 Now their community-testing package is out of date already - DBeaver has released 4.3.3, and 4.3.3.1 in recent days. I've updated my PR to 4.3.3.1, since I'm using this personally to install on my work and home machine.

The aur community package is still on 4.2.5.

I've been using linux for 1.5 years now but am brand new to contributing - can I ask some questions?

* Is it unacceptable for Antergos to run duplicates? Perhaps ours would stay up to date faster? Or even if the aur package ends up more up to date months from now - bottom line is that there's more chances that users get the updates in one channel or another?  Preferably there is only 1 channel that stays up to date though, but what do you do if something is poorly maintained?

* If we do not want to duplicate, I am also willing to help maintain the aur package, do you know how I could go about offering that support? Antergos was very easy to see - Github pull-request and done.

Thanks for reviewing!

**Comment by sum01** [comment]
Well the AUR pkgbuild isn't flagged out-of-date, so it's understandable if the maintainer doesn't know it needs an update. The simplist way would be to flag out-of-date, but if you absolutely *must* have the newest version, then it's easier to just use your own personal PKGBUILD like you're doing now.

You could also request co-maintainership on the AUR pkg, and update it as you see fit.

As for Antergos, I have no clue if they have anything against duplicates.

**Comment by CurtisBelt** [comment]
It was marked out of date back in November according to https://www.archlinux.org/packages/community/x86_64/dbeaver/ -- is that the correct link?

To their credit, the testing 4.3.2 is a new development in the last few weeks. But the history shows the updates for that package were slow before.

Have I jumped the gun on how cutting-edge the rolling updates are supposed to be? I assumed that the intent is to get new (stable) releases ASAP, and some people even indulge in "-git" packages that constantly update you to the latest commit.

> As for Antergos, I have no clue if they have anything against duplicates.

Do you know who we should ask? @lots0logs ?

**Comment by sum01** [comment]
I was referencing the AUR pkg, but it seems that's the enterprise editon.

Here's a worse example in official repos: the `db` package has been on v5 since 2015, but v6.2 is the newest. I marked out-of-date months ago, and it was unflagged with no email as to why. No idea why they do what they do 🤔

**Comment by lots0logs** [comment]
@CurtisBelt I've been really busy lately. Sorry! Things should calm down next week though.

**Comment by CurtisBelt** [comment]
@lots0logs Is there something blocking this?

**Pull request closed without merging**
