### PR TITLE
Removed xscreensaver dependency

### PR DESCRIPTION
**Pull request by vsilvar**
Removed the xscreensaver dependency from gnome-shell-extension-status-menu-buttons

### CODE REVIEW

**Comment by lots0logs** [comment]
What's the purpose of this change?

**Comment by vsilvar** [comment]
Allowing the xscreensaver package to be removed without the nag of being a dependency, when it isn't needed for gnome-shell-extension-status-menu-buttons

**Comment by lots0logs** [comment]
Actually it is needed for light-locker to handle the lockscreen properly. Truth be told xscreensaver should be a dependency of light-locker and not this extension but since light-locker is packaged by Arch we have no control over it.

**Comment by vsilvar** [comment]
After testing I was unable to notice any difference between having xscreensaver installed or not.

**Pull request closed without merging**
