### PR TITLE
update to latest version 1.3.1

### PR DESCRIPTION
**Pull request by killajoe**
as usual ;)
builds fine and runs without any error..

@karasu @lots0logs

### CODE REVIEW

**Comment by killajoe** [comment]
https://forum.antergos.com/topic/9166/why-does-antergos-contain-its-own-version-of-etcher/5

**Comment by IsaakGroepT** [comment]
I rather want removal of this package, because AUR's is well maintained. This one has been outdated a long time so it seems more like a burden to the devs than an advantage

**Comment by killajoe** [comment]
only because to have it aviable as a package, also for users not using AUR ;)

**Comment by IsaakGroepT** [comment]
Ooh, I see the advantage there. But isn't it more wise to rename it to something Antergos only, instead of having it conflict with AUR's package, which is kept more updated? Something like etcher-antergos

**Comment by killajoe** [comment]
you can build and install from AUR as you like. And we do discuss this already at the forum...

**Pull request merged**
