### PR TITLE
added the Deepin related packages

### PR DESCRIPTION
**Pull request by stratus-ss**
These are the package builds developed in conjunction with the Deepin project

### CODE REVIEW

**Comment by lots0logs** [comment]
:dizzy_face: WOW, I had no idea it was this many packages. I'll start reviewing them ASAP.

**Comment by karasu** [comment]
すごい (awesome!)

**Comment by stratus-ss** [comment]
For thoroughness I started trying to build these packages on a clean environment and have found some mistakes. 

I am going to do a better, more thorough job of documenting the process of making packages from scratch including build order. I will resubmit a pull request when this is done

**Comment by lots0logs** [comment]
Okay..definitely make sure the makedepends and depends are correct so that the build order can be determined by the build server. Also, if any of the packages utilize a test if `$CARCH = i686` or similar for any pkgbuild variables (source, depends, makedepends,etc) replace that with the new architecture specific variables (source_x86_64, source_i686, depends_x86_64, etc).

**Pull request closed without merging**
