### PR TITLE
etcher: update PKGBUILD to 1.4.8-1

### PR DESCRIPTION
**Pull request by killajoe**
copy from latest AUR version change 1.4.4-3 >> 1.4.8-1
Builds fine here ;)

@karasu @lots0logs 

But it now includes commercials, what is looking realy bad:
bildschirmfoto vom 2018-12-04 15-17-00

### CODE REVIEW

**Comment by killajoe** [comment]
I do ask at there forum about: 
https://forums.balena.io/t/new-etcher-shows-picture-and-link-to-tutorials/4733

**Comment by killajoe** [comment]
any problems with updating?

**Comment by karasu** [comment]
@killajoe to be honest, that "tutorial" looks awful in a serious application. On the other hand, it's a small price to pay to use that app. I will update it asap.

**Comment by killajoe** [comment]
https://github.com/Antergos/antergos-packages/pull/433

**Pull request closed without merging**
