### PR TITLE
fix #295 - gitkraken 3.4.0

### LINKED ISSUE #295: Gitkraken 3.4.0-1 broken - libpsl.so.5: cannot open shared object file
When trying to start gitkraken I get

```
/opt/gitkraken/gitkraken: error while loading shared libraries: libpsl.so.5: cannot open shared object file: No such file or directory
```

People here are seeing the same issue, when it was installed from Antergos https://aur.archlinux.org/packages/gitkraken/ - seems OK from AUR.

### PR DESCRIPTION
**Pull request by schmunk42**
Details: #295

see also https://github.com/Azd325/gitkraken/commit/55ad421e3eb55d9321a0ce0972877354f2e374c6#diff-9a18cd878ea1aa536e9402ffdcfdf78f

### CODE REVIEW

**Comment by starkers** [comment]
I was about to PR the same thing. Thanks

Just to confirm...Just did the same fix here and it `works[tm]`

**Comment by starkers** [comment]
..actually this will break I just noticed u didn't update the sha256sum in the `PKGBUILD`

```
-            '6130330390309394823f7b4f234423f7f111c5e4ef20706ea185f57a2f9bc5b0')
+            'bbfbfa798b9bd68a6ecf0485fa36a470660af4895ff3e26b4719f467da2fe464')
```

**Comment by CurtisBelt** [comment]
I believe we can remove libcurl-openssl-1.0 from dependencies as well.

**Comment by CurtisBelt** [comment]
@starkers 

When you tested this, did the update override your `usr/bin/gitkraken` file correctly? I ran this fix as well, but I had to go manually edit `/usr/bin/gitkraken`. Maybe it was something I did.

**Comment by starkers** [comment]
`gitkraken-launcher` correctly became my `/usr/bin/gitkraken`

**Comment by schmunk42** [comment]
I am pretty new to Antergos & Arch, so let me know if there needs action to be taken from my side or just update this PR on GitHub.

**Comment by starkers** [comment]
Ok so the AUR will try make sure the files it processes haven't been tempered with. It run "sha256" on the files to get unique fingerprints of them.. So basically if you've changed a file you need to update those signatures too.

It's a little annoying but it means users can trust it :)

I think you just need to update the last sha in the PKGBUILD file. Afterwards, run "makepkg -si" in the same directory, this will test that the build and install works.. 

In pretty new to AUR too ;)

**Comment by killajoe** [comment]
3.4.1 is the version on AUR... so version needs to be updated too...

**Comment by CurtisBelt** [comment]
@schmunk42 I made a PR on your PR to update us to 3.4.1 and fix everything else :+1:  https://github.com/schmunk42/antergos-packages/pull/1

**Comment by lots0logs** [comment]
Thanks guys!

**Pull request merged**
