### PR TITLE
Revert "Update PKGBUILD"

### PR DESCRIPTION
**Pull request by lots0logs**
Reverts Antergos/antergos-packages#123

We cannot do this. Makepkg does not support depending on a package group.

### CODE REVIEW

**Comment by Wyn10** [comment]
Aw shucks...that group is needed for configuring qtcurve via Plasma settings.

**Comment by lots0logs** [comment]
@Wyn10  Why is that exactly? Surely it doesnt need the entire group including the lib32 pkgs? What error message are you getting?

**Comment by karasu** [comment]
Geez, I didn't realise it was a package group. Sorry.

**Comment by Wyn10** [comment]
@lots0logs There is no error, qtcurve simply wouldnt be customizable via the plasma settings.  I'll have to check what package is used for it.

**Pull request merged**
