### PR TITLE
corebird: update PKGBUILD

### PR DESCRIPTION
**Pull request by Mikaela**
I am not comfortable with my packaging skills, so please check this
before merging.

### CODE REVIEW

**Comment by lots0logs** [comment]
Thanks for the PR but actually we need to set this one up so its monitored for releases by the build server automatically. I'll get it done later today. Cheers!

**Comment by Mikaela** [comment]
When will this come to force? It has been 12 hours and I am just annoyed by the message `warning: corebird: local (1.3-0) is newer than antergos (1.2.2-1)`.

**Comment by Wyn10** [comment]
@Mikaela https://build.antergos.com/build/4196

http://wynsrv.antergos.info/antergos-staging/x86_64/corebird-1.3-1-x86_64.pkg.tar.xz

**Comment by Mikaela** [comment]
Sorry for late reply (build.antergos.com is not very mobile-friendly).

I don't see any build errors there with quick glance, but I appear to still be gettin the message `warning: corebird: local (1.3-0) is newer than antergos (1.2.2-1)`. Is there something wrong with the mirrors again?

**Comment by Wyn10** [comment]
@Mikaela 

The second link I posted shows it's in the staging repo.

**Pull request closed without merging**
