### PR TITLE
Rename themes group to antergos-themes

### PR DESCRIPTION
**Pull request by artur9010**

### CODE REVIEW

**Comment by lots0logs** [comment]
What is the reasoning behind this change? I really do not want to prefix the package groups if it can be avoided.

**Comment by artur9010** [comment]
Other repositories can have such a group "themes".

**Comment by lots0logs** [comment]
Which repositories?

**Comment by Wyn10** [comment]
@lots0logs I can see what he means on aur when searching themes.  There's usually a prefix for each theme.

https://aur.archlinux.org/packages/?O=0&K=themes

**Comment by lots0logs** [comment]
@Wyn10 No, that's not the same thing. Groups are only for packages hosted in pacman repos (not AUR packages).

**Comment by Wyn10** [comment]
@lots0logs Ah okay.

**Comment by karasu** [comment]
Let's close this, then.

**Pull request closed without merging**
